filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.name: "logitrack"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              multiline:
                pattern: '^[[:space:]]'
                negate: true
                match: after

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

logging.level: info
